AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A sample SAM template for deploying Lambda functions using CodePipeline.

Resources:
  # Details about the myDateTimeFunction Lambda function
  myDateTimeFunctionPipeline:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src
      Handler: myDateTimeFunction.handler
      Runtime: nodejs10.x
      Role: "arn:aws:iam::530694037299:role/lambda-poc-role"